return {
  --   {
  --     'robitx/gp.nvim',
  --     dependencies = { 'folke/which-key.nvim' },
  --
  --     config = function()
  --       -----------------------------------------------------------------
  --       -- Helper function: get_code_selection_or_buffer
  --       --
  --       -- This function returns a string containing:
  --       --   * The currently selected text, if a selection exists,
  --       --   * Otherwise, the entire buffer's contents.
  --       --
  --       -- It uses Neovim's API to check the marks for the start ('<')
  --       -- and end ('>') of the visual selection. If no meaningful
  --       -- selection is found (i.e. same start and end positions),
  --       -- it falls back to retrieving all lines from the buffer.
  --       -----------------------------------------------------------------
  --       local function get_code_selection_or_buffer()
  --         -- Retrieve starting mark ('<') and ending mark ('>') for current selection.
  --         local start_line, start_col = unpack(vim.api.nvim_buf_get_mark(0, '<'))
  --         local end_line, end_col = unpack(vim.api.nvim_buf_get_mark(0, '>'))
  --
  --         local code_lines = nil
  --
  --         -- Check if a selection exists:
  --         if start_line ~= end_line or start_col ~= end_col then
  --           -- If there is a selection, get the selected lines.
  --           -- Note: Lua indices for lines start at 1, so subtract one.
  --           code_lines = vim.api.nvim_buf_get_lines(0, start_line - 1, end_line, false)
  --         else
  --           -- Otherwise, get all lines from the current buffer.
  --           code_lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
  --         end
  --
  --         -- Concatenate the lines into one single string with newline separators.
  --         return table.concat(code_lines, '\n')
  --       end
  --
  --       -----------------------------------------------------------------
  --       -- Plugin Configuration Table for gp.nvim and its hooks.
  --       -----------------------------------------------------------------
  --       local conf = {
  --         -- Retrieve the OpenAI API key from the macOS Keychain
  --         openai_api_key = { 'security', 'find-generic-password', '-a', os.getenv 'USER', '-s', 'OPENAI_API_KEY', '-w' },
  --         hooks = {
  --           -----------------------------------------------------------------
  --           -- Explain hook:
  --           --
  --           -- This hook builds a prompt for explaining code.
  --           -- It uses the helper function get_code_selection_or_buffer to
  --           -- determine the code snippet (either the selection or the entire
  --           -- buffer) then creates a message template and passes it on.
  --           -----------------------------------------------------------------
  --           Explain = function(gp, params)
  --             -- Get the code snippet, either selection or the full buffer.
  --             local selection = get_code_selection_or_buffer()
  --
  --             -- Build a prompt template that includes code syntax highlighting.
  --             local template = 'I have the following code from {{filename}}:\n\n'
  --               .. '```lua\n'
  --               .. selection
  --               .. '\n```\n\n'
  --               .. 'Please respond by explaining the code above.  Be short and concise. Use markdown formatting and code blocks where appropriate.'
  --
  --             -- Retrieve the chat agent and forward the prompt. The output will
  --             -- be shown in a popup window.
  --             local agent = gp.get_chat_agent()
  --             gp.Prompt(params, gp.Target.popup, agent, template)
  --           end,
  --
  --           -----------------------------------------------------------------
  --           -- CodeReview hook:
  --           --
  --           -- This hook is similar to Explain but builds a prompt for a
  --           -- code review, asking for suggestions for improvements.
  --           -----------------------------------------------------------------
  --           CodeReview = function(gp, params)
  --             -- Get the code snippet (selected text or the whole buffer).
  --             local selection = get_code_selection_or_buffer()
  --
  --             -- Build a prompt template for a code review.
  --             local template = 'I have the following code from {{filename}}:\n\n'
  --               .. '```lua\n'
  --               .. selection
  --               .. '\n```\n\n'
  --               .. 'Please analyze for code smells and suggest improvements. Be short and concise. Use markdown formatting and code blocks where appropriate.'
  --
  --             -- Retrieve the chat agent and initiate the prompt in an 'enew'
  --             -- markdown buffer.
  --             local agent = gp.get_chat_agent()
  --             gp.Prompt(params, gp.Target.enew 'markdown', agent, template)
  --           end,
  --
  --           -- Documentation hook:
  --           --
  --           -- Creates documentation for the entity (code, function, or class) located at the current cursor position.
  --
  --           -----------------------------------------------------------------
  --           -- BufferChatNew hook:
  --           --
  --           -- This hook opens a new chat using the entire current buffer as context.
  --           -----------------------------------------------------------------
  --           BufferChatNew = function(gp, _)
  --             vim.api.nvim_command('%' .. gp.config.cmd_prefix .. 'ChatNew')
  --           end,
  --         },
  --       }
  --
  --       require('gp').setup(conf)
  --
  --       local wk = require 'which-key'
  --       wk.add({
  --         -- group label for the prefix
  --         { '<C-g>', group = '🤖GPT' },
  --
  --         -- Custom hooks
  --         { '<C-g>x', '<cmd>GpExplain<CR>', desc = 'Explain selection', mode = { 'n', 'i', 'v' } },
  --         { '<C-g>v', '<cmd>GpCodeReview<CR>', desc = 'Code review selection', mode = { 'n', 'i', 'v' } },
  --         { '<C-g>B', '<cmd>GpBufferChatNew<CR>', desc = 'Chat with buffer', mode = { 'n', 'i' } },
  --         { '<C-g>D', '<cmd>GpDocumentChatNew<CR>', desc = 'Chat with documentation', mode = { 'n', 'i' } },
  --
  --         -- Chat
  --         { '<C-g>c', '<cmd>GpChatNew<CR>', desc = 'New chat', mode = { 'n', 'i' } },
  --         { '<C-g>t', '<cmd>GpChatToggle popup<CR>', desc = 'Toggle chat (popup)', mode = { 'n', 'i' } },
  --         { '<C-g>f', '<cmd>GpChatFinder<CR>', desc = 'Chat finder', mode = { 'n', 'i' } },
  --         { '<C-g>c', ":'<,'>GpChatNew<CR>", desc = 'Chat with selection', mode = 'v' },
  --         { '<C-g>p', ":'<,'>GpChatPaste<CR>", desc = 'Paste selection to chat', mode = 'v' },
  --
  --         -- Edit-in-place
  --         { '<C-g>r', '<cmd>GpRewrite<CR>', desc = 'Rewrite (prompt)', mode = { 'n', 'i' } },
  --         { '<C-g>a', '<cmd>GpAppend<CR>', desc = 'Append after', mode = { 'n', 'i' } },
  --         { '<C-g>b', '<cmd>GpPrepend<CR>', desc = 'Prepend before', mode = { 'n', 'i' } },
  --         { '<C-g>r', ":'<,'>GpRewrite<CR>", desc = 'Rewrite selection', mode = 'v' },
  --         { '<C-g>a', ":'<,'>GpAppend<CR>", desc = 'Append selection', mode = 'v' },
  --         { '<C-g>b', ":'<,'>GpPrepend<CR>", desc = 'Prepend selection', mode = 'v' },
  --         { '<C-g>i', ":'<,'>GpImplement<CR>", desc = 'Implement from comments', mode = 'v' },
  --
  --         -- Shortcut to generate API documentation
  --
  --         -- Layout variants
  --         { '<C-g><C-x>', '<cmd>GpChatNew split<CR>', desc = 'New chat (split)', mode = { 'n', 'i' } },
  --         { '<C-g><C-v>', '<cmd>GpChatNew vsplit<CR>', desc = 'New chat (vsplit)', mode = { 'n', 'i' } },
  --         { '<C-g><C-t>', '<cmd>GpChatNew tabnew<CR>', desc = 'New chat (tab)', mode = { 'n', 'i' } },
  --
  --         -- Agents & control
  --         { '<C-g>n', '<cmd>GpNextAgent<CR>', desc = 'Next agent', mode = { 'n', 'i' } },
  --         { '<C-g>l', '<cmd>GpSelectAgent<CR>', desc = 'Select agent', mode = { 'n', 'i' } },
  --         { '<C-g>s', '<cmd>GpStop<CR>', desc = 'Stop generation', mode = { 'n', 'i' } },
  --       }, { noremap = true, silent = true, nowait = true })
  --     end,
  --   },
}
